# 导入原版 3D/2D 放大节点的映射 (倍数模式)
from .minimax_h3_latent_upscaler_3d import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_3D,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_3D,
)
from .minimax_h3_latent_upscaler_2d import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_2D,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_2D,
)

# 导入社区补全的变体节点
from .H3_latent_upscaler_resolution import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_RES,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_RES,
)
from .H3_latent_upscaler_megapixels import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_MP,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_MP,
)
from .H3_latent_upscaler_3d_v3 import (
    NODE_CLASS_MAPPINGS as NODE_CLASS_MAPPINGS_V3,
    NODE_DISPLAY_NAME_MAPPINGS as NODE_DISPLAY_NAME_MAPPINGS_V3,
)

# 合并所有节点映射 (后者覆盖前者，请保持期望的优先级)
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_3D)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_2D)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_RES)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_MP)
NODE_CLASS_MAPPINGS.update(NODE_CLASS_MAPPINGS_V3)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_3D)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_2D)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_RES)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_MP)
NODE_DISPLAY_NAME_MAPPINGS.update(NODE_DISPLAY_NAME_MAPPINGS_V3)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
